### ISSUE TITLE
Copy edit link on FR Secteurs page

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#22]
- [ ] Correct the spelling of Partenaires on the WordPress site

Current
<img width="405" alt="Screen Shot 2021-06-18 at 20 25 42" src="https://user-images.githubusercontent.com/13530245/122608000-7475cf80-d049-11eb-936e-11998f814157.png">

WordPress
<img width="426" alt="Screen Shot 2021-06-18 at 20 24 24" src="https://user-images.githubusercontent.com/13530245/122607894-45f7f480-d049-11eb-8dc5-b853559f1776.png">

**Comment by adambard1** [comment]
@ajazmi this was not an error by devs, I just fixed it on the current site

**Comment by ajazmi** [comment]
@adambard1 Fixed

**Comment by adambard1** [comment]
@ajazmi it is not fixed on the front end. I don't know if that is what you meant by 'dev site'?
<img width="802" alt="Screen Shot 2021-06-21 at 13 35 45" src="https://user-images.githubusercontent.com/13530245/122762862-c007c380-d26b-11eb-8b2e-6f61cd3879ec.png">

**Comment by ajazmi** [comment]
@adambard1 Yes, dev site refers new site we are working on https://midisgroup.thinkdesign.com/fr/secteurs/.   It has been fixed at our side. We can see link correctly redirecting to appropriate section. It might be temp cache issue.

**Comment by adambard1** [comment]
> It might be temp cache issue

If it is, I don't know how to clear it @ajazmi. I have cleared history/cache/cookies, etc.
Still seeing the same copy
<img width="1280" alt="Screen Shot 2021-06-22 at 12 59 32" src="https://user-images.githubusercontent.com/13530245/122920916-e68f3280-d32f-11eb-93c8-e20bbd018f17.png">

**Comment by adambard1** [comment]
This issue was not about the link not working properly, it was about the spelling of the link.
I have fixed that on the back end
